version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 99
  labels:
  - dependencies
  ignore:
  - dependency-name: "@babel/*"
    versions:
    - ">= 0"
  - dependency-name: babel-plugin-preval
    versions:
    - ">= 3.0"
  - dependency-name: core-js
    versions:
    - ">= 0"
  - dependency-name: "@date-io/*"
    versions:
    - ">= 0"
  - dependency-name: jss-*
    versions:
    - ">= 0"
  - dependency-name: raw-loader
    versions:
    - ">= 0"
  - dependency-name: react-dom
    versions:
    - ">= 0"
  - dependency-name: react-is
    versions:
    - ">= 0"
  - dependency-name: react-test-renderer
    versions:
    - ">= 0"
  - dependency-name: tslint
    versions:
    - 5.x
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - ">= 0"
  - dependency-name: "@types/eslint"
    versions:
    - 7.2.7
    - 7.2.9
  - dependency-name: react-spring
    versions:
    - 9.0.0
    - 9.1.0
  - dependency-name: aws-sdk
    versions:
    - 2.831.0
    - 2.834.0
    - 2.839.0
    - 2.843.0
    - 2.848.0
    - 2.853.0
    - 2.858.0
    - 2.863.0
    - 2.874.0
    - 2.884.0
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: framer-motion
    versions:
    - 3.2.1
    - 3.3.0
    - 3.6.2
    - 3.7.0
    - 4.0.0
    - 4.0.3
    - 4.1.2
    - 4.1.3
  - dependency-name: "@testing-library/dom"
    versions:
    - 7.29.4
    - 7.29.6
    - 7.30.0
    - 7.30.1
    - 7.30.3
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: "@chakra-ui/system"
    versions:
    - 1.1.7
    - 1.2.1
    - 1.3.1
    - 1.4.0
    - 1.5.1
    - 1.6.0
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.10
    - 9.0.6
    - 9.0.7
    - 9.0.8
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.21.2
    - 5.23.0
    - 5.24.2
    - 5.24.3
    - 5.25.1
    - 5.27.1
    - 5.28.0
    - 5.30.0
  - dependency-name: "@types/marked"
    versions:
    - 1.2.2
    - 2.0.0
    - 2.0.1
  - dependency-name: rollup
    versions:
    - 2.36.2
    - 2.38.2
    - 2.39.0
    - 2.40.0
    - 2.41.2
    - 2.42.2
    - 2.43.1
    - 2.44.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.21
    - 14.14.22
    - 14.14.28
    - 14.14.31
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: "@types/webpack"
    versions:
    - 4.41.26
    - 5.0.0
  - dependency-name: stylis
    versions:
    - 4.0.7
    - 4.0.8
    - 4.0.9
  - dependency-name: karma
    versions:
    - 6.0.1
    - 6.0.3
    - 6.1.0
    - 6.1.1
    - 6.2.0
    - 6.3.1
  - dependency-name: jsdom
    versions:
    - 16.5.1
    - 16.5.2
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
  - dependency-name: cross-fetch
    versions:
    - 3.1.0
    - 3.1.2
  - dependency-name: playwright
    versions:
    - 1.8.0
    - 1.8.1
    - 1.9.1
    - 1.9.2
  - dependency-name: "@types/draft-js"
    versions:
    - 0.11.0
  - dependency-name: react-number-format
    versions:
    - 4.4.4
    - 4.5.1
  - dependency-name: theme-ui
    versions:
    - 0.3.5
    - 0.6.0
  - dependency-name: clean-css
    versions:
    - 5.0.1
    - 5.1.0
    - 5.1.1
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.8
  - dependency-name: "@types/jsdom"
    versions:
    - 16.2.6
    - 16.2.7
  - dependency-name: "@popperjs/core"
    versions:
    - 2.8.2
    - 2.8.6
    - 2.9.0
    - 2.9.1
  - dependency-name: svgo
    versions:
    - 2.0.3
    - 2.1.0
    - 2.2.1
    - 2.2.2
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.0.3
    - 5.1.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: date-fns
    versions:
    - 2.17.0
    - 2.19.0
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.3
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/luxon"
    versions:
    - 1.25.1
    - 1.25.2
    - 1.26.0
    - 1.26.1
    - 1.26.2
  - dependency-name: "@types/prettier"
    versions:
    - 2.1.6
    - 2.2.1
    - 2.2.2
  - dependency-name: material-ui-popup-state
    versions:
    - 1.7.2
  - dependency-name: danger
    versions:
    - 10.6.0
    - 10.6.1
    - 10.6.2
    - 10.6.3
  - dependency-name: csstype
    versions:
    - 3.0.6
    - 3.0.7
  - dependency-name: recharts
    versions:
    - 2.0.3
    - 2.0.4
    - 2.0.6
    - 2.0.7
    - 2.0.8
  - dependency-name: notistack
    versions:
    - 1.0.3
    - 1.0.5
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
  - dependency-name: "@rollup/plugin-replace"
    versions:
    - 2.4.0
    - 2.4.1
  - dependency-name: concurrently
    versions:
    - 6.0.0
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.9.0
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.1
  - dependency-name: envinfo
    versions:
    - 7.7.4
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
  - dependency-name: dtslint
    versions:
    - 4.0.7
  - dependency-name: mocha
    versions:
    - 8.3.0
  - dependency-name: "@types/chai"
    versions:
    - 4.2.15
  - dependency-name: "@emotion/styled"
    versions:
    - 11.1.5
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
  - dependency-name: "@types/yargs"
    versions:
    - 16.0.0
  - dependency-name: emoji-regex
    versions:
    - 9.2.1
  - dependency-name: marked
    versions:
    - 1.2.8
  - dependency-name: autoprefixer
    versions:
    - 10.2.3
    - 10.2.4
  - dependency-name: jss
    versions:
    - 10.5.1
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.4.0
  - dependency-name: sinon
    versions:
    - 9.2.4
  - dependency-name: react-jss
    versions:
    - 10.5.1
  - dependency-name: "@fortawesome/fontawesome-svg-core"
    versions:
    - 1.2.34
  - dependency-name: "@fortawesome/free-solid-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: markdown-to-jsx
    versions:
    - 7.1.1
  - dependency-name: globby
    versions:
    - 11.0.2
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
  - dependency-name: "@types/sinon"
    versions:
    - 9.0.10
  - dependency-name: "@emotion/react"
    versions:
    - 11.1.4
